import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export interface DailyLog {
  date: string;
  lunch: boolean;
  dinner: boolean;
  guestLunch: number;
  guestDinner: number;
}

export interface MemberReport {
  memberId: string;
  memberName: string;
  phone: string;
  prevBalance: number;
  advanceDeposit: number;
  finalDeposit: number;
  remainingDeposit: number;
  totalMeals: number;
  totalCost: number;
  currentBalance: number;
  dailyLogs: DailyLog[];
  photoBase64?: string;
}

export const generatePDF = (item: MemberReport, selectedMonth: string): jsPDF => {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'mm',
    format: 'a4'
  });

  const monthName = format(new Date(selectedMonth), 'MMMM yyyy');

  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('RiceManager', 15, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('DETAILED MONTHLY STATEMENT', 150, 25);

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Member Information', 15, 55);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${item.memberName}`, 15, 63);
  doc.text(`Phone: ${item.phone}`, 15, 69);
  doc.text(`Billing Month: ${monthName}`, 15, 75);
  doc.text(`Statement Date: ${format(new Date(), 'dd MMM, yyyy')}`, 15, 81);

  autoTable(doc, {
    startY: 90,
    head: [['Financial Summary', 'Amount (BDT)']],
    body: [
      ['Previous Balance (Brought Forward)', `${item.prevBalance >= 0 ? '+' : ''}${item.prevBalance}`],
      ['Advance Deposit', `+${item.advanceDeposit}`],
      ['Final Settlement', `+${item.finalDeposit}`],
      ['Total Available Funds', `${item.remainingDeposit}`],
      [`Total Meals Consumed (${item.totalMeals})`, `-${item.totalCost}`],
    ],
    theme: 'grid',
    styles: { fontSize: 11, cellPadding: 6 },
    headStyles: { fillColor: [71, 85, 105], textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFillColor(item.currentBalance >= 0 ? 240 : 254, item.currentBalance >= 0 ? 253 : 242, item.currentBalance >= 0 ? 244 : 242);
  doc.rect(15, finalY, 180, 20, 'F');
  doc.setTextColor(item.currentBalance >= 0 ? 5 : 185, item.currentBalance >= 0 ? 150 : 28, item.currentBalance >= 0 ? 105 : 28);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Closing Balance:', 25, finalY + 13);
  doc.text(`${item.currentBalance} TK`, 185, finalY + 13, { align: 'right' });

  doc.addPage();
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, 210, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('Daily Meal Consumption Log', 15, 13);

  autoTable(doc, {
    startY: 25,
    head: [['Date', 'Lunch', 'Dinner', 'Guest', 'Total']],
    body: item.dailyLogs.map(log => [
        format(new Date(log.date), 'dd MMM (EEE)'),
        log.lunch ? '1' : '-',
        log.dinner ? '1' : '-',
        (log.guestLunch + log.guestDinner) > 0 ? (log.guestLunch + log.guestDinner) : '-',
        (log.lunch ? 1 : 0) + (log.dinner ? 1 : 0) + log.guestLunch + log.guestDinner
    ]),
    theme: 'striped',
    styles: { fontSize: 9, halign: 'center' },
    headStyles: { fillColor: [100, 116, 139] },
    columnStyles: { 0: { halign: 'left', fontStyle: 'bold' } }
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount} | Generated by RiceManager`, 105, 285, { align: 'center' });
  }

  return doc;
};
